set echo on
spool ../log/analyze_tab_hkei1.log
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') "開始時刻" FROM DUAL;

-- ■テーブルアナライズ
ANALYZE TABLE M_GAMEN ESTIMATE STATISTICS SAMPLE 10 PERCENT;
ANALYZE TABLE M_SHTML ESTIMATE STATISTICS SAMPLE 10 PERCENT;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') "終了時刻" FROM DUAL;
spool off
set echo off

