SELECT 
	OBJECT_TYPE
	,OBJECT_NAME
FROM 
	USER_OBJECTS
WHERE 
		STATUS = 'INVALID'
	AND OBJECT_TYPE IN ('FUNCTION','PROCEDURE','PACKAGE','PACKAGE BODY','TRIGGER','VIEW')
ORDER BY 
	OBJECT_TYPE, OBJECT_NAME
;


